#!/bin/bash

# wrapdocker: runs as the container's ENTRYPOINT. Runs a daemon in the
# foreground if PORT is set to a port to listen on. Otherwise, runs the daemon
# in the background and the args or plain Bash in the foreground. 

# If we were given a PORT environment variable, exec startdocker which will block;
# otherwise, run it and wait for it to start up background Docker, and exec our
# arguments or a shell
if [ "$PORT" ]
then
	exec startdocker
else
	startdocker
	[[ $1 ]] && exec "$@"
	exec bash --login
fi
